### ISSUE TITLE
Friedman's H-Statistic

### ISSUE THREAD

**Issue by thiyangt** [christophM/iml#56] opened 2018-10-22 22:20 UTC
I created a random forest model using the randomForest package. The training set size I used to develop the random forest model is 500000. I would like to observe the two-way interaction using the Friedman's H statistic. Since my training set is large I took a subset of the training set to calculate Friedman's H statistic. 
My code is as follow

predictor = Predictor$new(rf, data=x_subset, y=y_subset)
interact = Interaction$new(predictor, feature = "x1")

In the above code x_subset  and y_subset are created based on a subset of training data.
But, to my surprise for some interactions I received values greater than 1.  I thought Friedman test value should be in between 0 and 1.

**Comment by christophM** [comment] 2018-10-23 14:11
How big are the values?
Per chance they can be above 1, but shouldnt be much. 
What if you repeat the experiments?

**Comment by thiyangt** [comment] 2018-10-23 22:13
They are not too high. Maximum I observed for my dataset is 1.6.  May be rounding errors can result in values of H > 1. Further I observed NaN values. In that case, neither main effect is in the selected model (relative influence is zero), the result will be 0/0. This is discussed in `interact.gbm` function in `gbm` package.

**Comment by christophM** [comment] 2019-01-09 11:40
Closing because of missing reproducibility.

**Closed by christophM** 2019-01-09 11:40 UTC

**Comment by thiyangt** [comment] 2019-05-21 03:23
A minimal reproducible example :

> rf <- randomForest::randomForest(Species ~ ., data=iris)
> X <- iris[1:50, -5]
> Y <- iris[1:50, 5]
> predictor = Predictor$new(rf, data=X, y=Y, type = "prob")
> ia1 = Interaction$new(predictor, feature = "Sepal.Length")
> ia1
> plot(ia1)
